apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
- namespace.yaml
- configmap.yaml
- operator-service-account-rbac.yaml
- postgres-operator.yaml
- api-service.yaml

# files for WAL backup to S3
- pod_environment_configmap.yaml
patchesStrategicMerge:
  - "postgres-cm.yaml"
