apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-main-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "12"

  patroni:
    # synchronous_mode: false
    # synchronous_mode_strict: false
    pg_hba:
      - local     all          all                        trust
      - hostssl   all          +standby 127.0.0.1/32     pam
      - host      all          all       127.0.0.1/32     md5
      - hostssl   all          +standby ::1/128          pam
      - host      all          all       ::1/128          md5
      - local     replication  standby                    trust
      - hostssl   replication  standby   all              md5
      - hostnossl all          all       all              reject
      - hostssl   all          +standby all              pam
      - hostssl   all          all       all              md5

---

apiVersion: v1
kind: Service
metadata:
  name: acid-main-cluster-external
  namespace: postgres
  labels:
    application: spilo
    cluster-name: acid-main-cluster
    spilo-role: master
    statefulset.kubernetes.io/pod-name: acid-main-cluster-0
    team: acid

spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: acid-main-cluster
    spilo-role: master
    statefulset.kubernetes.io/pod-name: acid-main-cluster-0
    team: acid