apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-standby-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  postgresql:
    version: "12"
  standby:   # Make this a standby cluster and provide either the s3 bucket path of source cluster or the remote primary host for continuous streaming.
    # s3_wal_path: "s3://mybucket/spilo/acid-minimal-cluster/abcd1234-2a4b-4b2a-8c9c-c1234defg567/wal/14/" --> the url to S3 bucket containing the WAL archive of the remote primary.
    standby_host: "acid-main-cluster"
    standby_port: "5432"

  patroni:
    synchronous_mode: false #- Whether to use synchronous replication
    synchronous_mode_strict: false #Make the cluster READ ONLY if we don't have at least 1 synchronous replica.
    pg_hba:
      - local     all          all                        trust
      - hostssl   all          +standby 127.0.0.1/32     pam
      - host      all          all       127.0.0.1/32     md5
      - hostssl   all          +standby ::1/128          pam
      - host      all          all       ::1/128          md5
      - local     replication  standby                    trust
      - hostssl   replication  standby   all              md5
      - hostnossl all          all       all              reject
      - hostssl   all          +standby all              pam
      - hostssl   all          all       all              md5

---  

apiVersion: v1
kind: Service
metadata:
  name: acid-standby-cluster-external
  namespace: postgres
  labels:
    application: spilo
    cluster-name: acid-standby-cluster
    spilo-role: replica
    statefulset.kubernetes.io/pod-name: acid-standby-cluster-1
    team: acid

spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: acid-standby-cluster
    spilo-role: replica
    statefulset.kubernetes.io/pod-name: acid-standby-cluster-1
    team: acid